package com.view;

import com.controller.ClaimController;
import com.controller.PolicyController;
import com.model.Claim;
import com.model.Policy;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author supun
 */
public class AddClaim extends javax.swing.JInternalFrame {
Date date;
    /**
     * Creates new form AddClaim
     */
    public AddClaim() {
        initComponents();
        rightLabel.setVisible(false);
        closeLabel.setVisible(false);
        rightLabel.setOpaque(true);
        closeLabel.setOpaque(true);
    try {
        claimIdTextField.setText(generateClaimId());
    } catch (SQLException | ClassNotFoundException ex) {
        Logger.getLogger(AddClaim.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String currentDate = dateFormat.format(date);
        dateTextField.setText(currentDate);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        claimIdTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        claimAmountTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        closeLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descreptionTextArea = new javax.swing.JTextArea();
        rightLabel = new javax.swing.JLabel();
        policyIdTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nicTextField = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cancelButton.setText("Cancel");

        jLabel7.setText("Date");

        claimIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claimIdTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("Droid Serif", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Claim Request Form");

        claimAmountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claimAmountTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Claim Amount");

        jLabel2.setText("Policy ID");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        closeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/crossout.png"))); // NOI18N

        jLabel3.setText("NIC");

        jLabel4.setText("Claim ID");

        descreptionTextArea.setColumns(20);
        descreptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descreptionTextArea);

        rightLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/Check.png"))); // NOI18N

        policyIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                policyIdTextFieldActionPerformed(evt);
            }
        });
        policyIdTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                policyIdTextFieldKeyReleased(evt);
            }
        });

        dateTextField.setEditable(false);
        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Description");

        nicTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dateTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(claimIdTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(claimAmountTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(policyIdTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nicTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(rightLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(policyIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(rightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(claimAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(claimIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(addButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void claimIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claimIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claimIdTextFieldActionPerformed

    private void nicTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicTextFieldActionPerformed
        String nic = nicTextField.getText();
        String policyId = policyIdTextField.getText();

        try {
            Policy policy = PolicyController.searchPolicy(policyId);
            if (policy != null && policy.getNic().equals(nic)) {
                rightLabel.setVisible(true);
                closeLabel.setVisible(false);
                System.out.println("true");

            } else {
                rightLabel.setVisible(false);
                closeLabel.setVisible(true);
                System.out.println("false");
            }

        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AddClaim.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nicTextFieldActionPerformed

    private void policyIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_policyIdTextFieldActionPerformed
        nicTextField.requestFocus();
    }//GEN-LAST:event_policyIdTextFieldActionPerformed

    private void policyIdTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_policyIdTextFieldKeyReleased

    }//GEN-LAST:event_policyIdTextFieldKeyReleased

    private void claimAmountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claimAmountTextFieldActionPerformed
     
    try {
        double claimAmount=Double.parseDouble(claimAmountTextField.getText());
       Claim claim = ClaimController.searchClaimAmount(policyIdTextField.getText());
       Policy policy = PolicyController.searchPolicy(policyIdTextField.getText());
        if (claim!=null) {
            double policyAmount = policy.getAmount();
            double totalClaim=claim.getClaimAmount();
            if ((totalClaim+Double.parseDouble(claimAmountTextField.getText()))<(policyAmount*0.7)) {
                JOptionPane.showMessageDialog(rootPane, "You can take Rs "+(policyAmount*0.70-(totalClaim+Double.parseDouble(claimAmountTextField.getText())))+" amount.. ");
                generateClaimId();
                descreptionTextArea.requestFocus();
                
                
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Sorry..You reached max Claim Amount\n..You can take only Rs"+(policyAmount*0.70-(totalClaim))+" Claim Amount");
            }
            
        } 
    } catch (SQLException | ClassNotFoundException ex) {
        Logger.getLogger(AddClaim.class.getName()).log(Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_claimAmountTextFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        Claim claim = new Claim(claimIdTextField.getText(),policyIdTextField.getText(),dateTextField.getText(),Double.parseDouble(claimAmountTextField.getText()),descreptionTextArea.getText());
        
    try {
        int res=ClaimController.addClaim(claim);
        if (res>0) {
            JOptionPane.showMessageDialog(rootPane, "Added");
            claimIdTextField.setText(generateClaimId());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Faild");
        }
    } catch (SQLException | ClassNotFoundException ex) {
        Logger.getLogger(AddClaim.class.getName()).log(Level.SEVERE, null, ex);
    }
      

    }//GEN-LAST:event_addButtonActionPerformed

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField claimAmountTextField;
    private javax.swing.JTextField claimIdTextField;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JTextArea descreptionTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nicTextField;
    public static javax.swing.JTextField policyIdTextField;
    private javax.swing.JLabel rightLabel;
    // End of variables declaration//GEN-END:variables

    
    public static String generateClaimId() throws SQLException, ClassNotFoundException {
        String lastId = ClaimController.getLastClaimId();

        if (lastId == null) {
            return "CI0001";
        } else {
            int num = Integer.parseInt(lastId.substring(2));
            num++;
            if (num < 10) {
                return "CI000" + num;
            } else if (num < 100) {
                return "CI00" + num;
            } else if (num < 1000) {
                return "CI0" + num;
            } else {
                return "CI" + num;
            }
        }

    }   
}
