/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.controller.CustomerController;
import com.controller.PolicyController;
import com.model.Policy;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sun.security.tools.KeyStoreUtil;

/**
 *
 * @author supun
 */
public class AddPolicy extends javax.swing.JInternalFrame {

    Date date;

    /**
     * Creates new form AddPolicy
     */
    public AddPolicy() {
        initComponents();
        nic1TextField.setText(AddCustomerDetails.nic);

        amountTextField.addItem("50000");
        amountTextField.addItem("1000000");
        amountTextField.addItem("1500000");
        amountTextField.addItem("2000000");
        amountTextField.addItem("2500000");
        amountTextField.addItem("3000000");
        amountTextField.addItem("3500000");
        amountTextField.addItem("4000000");
        date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String currentDate = dateFormat.format(date);
        dateTextField.setText(currentDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        submitAddClaim = new javax.swing.JButton();
        amount = new javax.swing.JLabel();
        nic = new javax.swing.JLabel();
        nic1TextField = new javax.swing.JTextField();
        policyIdTextField = new javax.swing.JTextField();
        policyRegistrationForm = new javax.swing.JLabel();
        medicalRadioButton = new javax.swing.JRadioButton();
        dateTextField = new javax.swing.JTextField();
        policyType = new javax.swing.JLabel();
        cancelAddClaim = new javax.swing.JButton();
        vehicleRadioButton = new javax.swing.JRadioButton();
        lifeRadioButton = new javax.swing.JRadioButton();
        dateAddClaim = new javax.swing.JLabel();
        policyID = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        amountTextField = new org.jdesktop.swingx.JXComboBox();

        jPanel1.setBackground(java.awt.Color.white);

        submitAddClaim.setText("Submit");
        submitAddClaim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAddClaimActionPerformed(evt);
            }
        });

        amount.setText("Amount");

        nic.setText("NIC");

        nic1TextField.setEditable(false);
        nic1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nic1TextFieldActionPerformed(evt);
            }
        });

        policyRegistrationForm.setBackground(java.awt.Color.white);
        policyRegistrationForm.setFont(new java.awt.Font("Droid Serif", 0, 36)); // NOI18N
        policyRegistrationForm.setText("Policy Registration Form");

        buttonGroup1.add(medicalRadioButton);
        medicalRadioButton.setText("MEDICAL");
        medicalRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalRadioButtonActionPerformed(evt);
            }
        });

        policyType.setText("Policy Type");

        cancelAddClaim.setText("Cancel");

        buttonGroup1.add(vehicleRadioButton);
        vehicleRadioButton.setText("VEHICLE");
        vehicleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(lifeRadioButton);
        lifeRadioButton.setText("LIFE");
        lifeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lifeRadioButtonActionPerformed(evt);
            }
        });

        dateAddClaim.setText("Date");

        policyID.setText("Policy ID");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/Business-owners-policy.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(policyType, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lifeRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vehicleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(medicalRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(amountTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(12, 12, 12))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(dateAddClaim, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(dateTextField))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(policyID, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(policyIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nic, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nic1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(submitAddClaim, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(cancelAddClaim, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(policyRegistrationForm, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(policyRegistrationForm, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nic1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(policyType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lifeRadioButton)
                            .addComponent(vehicleRadioButton)
                            .addComponent(medicalRadioButton))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(policyID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(policyIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateAddClaim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submitAddClaim)
                            .addComponent(cancelAddClaim))))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitAddClaimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitAddClaimActionPerformed
        try {
            String x = String.valueOf(amountTextField.getSelectedItem());
            Policy policy = new Policy(nic1TextField.getText(),policyIdTextField.getText(),findId(),Double.parseDouble(x),dateTextField.getText());
            
            int res = PolicyController.addPolicy(policy);
            if (res > 0) {
                JOptionPane.showMessageDialog(rootPane, "Added");
                policyIdTextField.setText("");
                //dateTextField.setText("");
                //amountTextField.se("");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Failed");
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AddPolicy.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_submitAddClaimActionPerformed

    private void lifeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lifeRadioButtonActionPerformed
        try {
            policyIdTextField.setText(generateLifePolicyId());
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AddPolicy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lifeRadioButtonActionPerformed

    private void vehicleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleRadioButtonActionPerformed
        try {
            policyIdTextField.setText(generateVehiclePolicyId());
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AddPolicy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_vehicleRadioButtonActionPerformed

    private void medicalRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalRadioButtonActionPerformed
        try {
            policyIdTextField.setText(generateMedicalPolicyId());
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AddPolicy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_medicalRadioButtonActionPerformed

    private void nic1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nic1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nic1TextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount;
    private org.jdesktop.swingx.JXComboBox amountTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelAddClaim;
    private javax.swing.JLabel dateAddClaim;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton lifeRadioButton;
    private javax.swing.JRadioButton medicalRadioButton;
    private javax.swing.JLabel nic;
    public static javax.swing.JTextField nic1TextField;
    private javax.swing.JLabel policyID;
    private javax.swing.JTextField policyIdTextField;
    private javax.swing.JLabel policyRegistrationForm;
    private javax.swing.JLabel policyType;
    private javax.swing.JButton submitAddClaim;
    private javax.swing.JRadioButton vehicleRadioButton;
    // End of variables declaration//GEN-END:variables

    public static String generateLifePolicyId() throws SQLException, ClassNotFoundException {
        String lastId = PolicyController.getLastLifePolicyId();

        if (lastId == null) {
            return "L0001";
        } else {
            int num = Integer.parseInt(lastId.substring(1));
            num++;
            if (num < 10) {
                return "L000" + num;
            } else if (num < 100) {
                return "L00" + num;
            } else if (num < 1000) {
                return "L0" + num;
            } else {
                return "L" + num;
            }
        }

    }

    public static String generateVehiclePolicyId() throws SQLException, ClassNotFoundException {
        String lastId = PolicyController.getLastVehiclePolicyId();

        if (lastId == null) {
            return "V0001";
        } else {
            int num = Integer.parseInt(lastId.substring(1));
            num++;
            if (num < 10) {
                return "V000" + num;
            } else if (num < 100) {
                return "V00" + num;
            } else if (num < 1000) {
                return "V0" + num;
            } else {
                return "V" + num;
            }
        }

    }

    public static String generateMedicalPolicyId() throws SQLException, ClassNotFoundException {
        String lastId = PolicyController.getLastMedicalPolicyId();

        if (lastId == null) {
            return "M0001";
        } else {
            int num = Integer.parseInt(lastId.substring(1));
            num++;
            if (num < 10) {
                return "M000" + num;
            } else if (num < 100) {
                return "M00" + num;
            } else if (num < 1000) {
                return "M0" + num;
            } else {
                return "M" + num;
            }
        }

    }

    private String findId() {
        if (lifeRadioButton.isSelected()) {
            return "Life";
        } else if (vehicleRadioButton.isSelected()) {
            return "Vehicle";
        } else if (lifeRadioButton.isSelected()) {
            return "Medical";

        }
        return null;
    }


}
